### ISSUE TITLE
get_stock_info function does not work with the given example

### ISSUE THREAD

**Issue by ashwathalvak** [AkiMosi/moneycontrolPy#1]
File "*****.py", line 18, in <module>
    stock_info = api.get_stock_info(url_stock,save_as_json=True)              #To extract the stock information
  File "/Users/aalva/Library/Python/3.8/lib/python/site-packages/moneycontrolPy/mcp.py", line 673, in get_stock_info
    perc = [float(re.findall(r"\d+\.*\d*", i)[0]) for i in temp]
  File "/Users/aalva/Library/Python/3.8/lib/python/site-packages/moneycontrolPy/mcp.py", line 673, in <listcomp>
    perc = [float(re.findall(r"\d+\.*\d*", i)[0]) for i in temp]

**Comment by AkiMosi** [comment]
@ashwathalvak Could you provide the snapshot of the output or the error that you are getting?

And this package was built a year ago, moneycontrol had several updates after that, so this package must have depreciated. Yet share the issue, I would try to update in my free time.

**Comment by prsnjthldr** [comment]
I am facing the same problem. Kindly fix it. Here I am providing the snapshot of the error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [18], in <cell line: 2>()
      1 url_stock = 'https://www.moneycontrol.com/india/stockpricequote/banks-private-sector/icicibank/ICI02'
----> 2 stock_info = api.get_stock_info(url_stock)

File ~\anaconda3\lib\site-packages\moneycontrolPy\mcp.py:673, in API.get_stock_info(self, url, save_as_json, file_path)
    671 values = [float(i.getText().strip()) for i in values]
    672 temp = [i.getText().strip() for i in soup.findAll("em", limit=2)]
--> 673 perc = [float(re.findall(r"\d+\.*\d*", i)[0]) for i in temp]
    675 to_return = {
    676     "bse_value": values[0],
    677     "bse_percent": perc[0],
   (...)
    680     "time_stamp": datetime.datetime.now().__str__(),
    681 }
    683 if save_as_json == True:

File ~\anaconda3\lib\site-packages\moneycontrolPy\mcp.py:673, in <listcomp>(.0)
    671 values = [float(i.getText().strip()) for i in values]
    672 temp = [i.getText().strip() for i in soup.findAll("em", limit=2)]
--> 673 perc = [float(re.findall(r"\d+\.*\d*", i)[0]) for i in temp]
    675 to_return = {
    676     "bse_value": values[0],
    677     "bse_percent": perc[0],
   (...)
    680     "time_stamp": datetime.datetime.now().__str__(),
    681 }
    683 if save_as_json == True:

IndexError: list index out of range

**Comment by AkiMosi** [comment]
Hi there,

I haven't maintained this repo for a while.
